### ISSUE TITLE
Autosave fix

### ISSUE THREAD

**Issue by Xengaroo** [TIS2020-FMFI/plazma#83]
Pri poslednom teste nastal error - 

Exception in thread Thread-2:
Traceback (most recent call last):
File "C:\Program Files (x86)\Python36-32\lib\threading.py", line 916, in _bootstrap_inner
self.run()
File "C:\Program Files (x86)\Python36-32\lib\threading.py", line 864, in run
self._target(*self._args, **self._kwargs)
File "Program.py", line 34, in execute_functions
exec(function)
File "<string>", line 1, in <module>
File "Program.py", line 188, in measure
self.file_manager.save_last_measurement()
File "C:\s\plazma\plazma\src\file_manager.py", line 186, in save_last_measurement
os.mkdir(filepath)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:/Users/admin/Desktop/plazma/piatok/continuous-db\\dobra kalibracia\\measurements'

**Comment by Xengaroo** [comment]
Opravené.
